[build]
  publish = "dist/"
  command = "npm run build"
  functions = "lambda/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://epic-perlman-fd3a96.netlify.com/*"
  to = "https://playman.jared.gq/:splat"
  status = 301
